### ISSUE TITLE
Code coverage has fallen after version upgrade.

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/oracle-contracts#965]

**Comment by SamAg19** [comment]
Looks like with solidity coverage 0.8.0+, the way they are counting branches has changed as the number of branches in the code coverage commit has increased compared to previous runs. We will have to go through all contracts once again and see whats not covered.

**Comment by SkandaBhat** [comment]
@SamAg19 please create a separate issue for this and we can track it separately.
